name: Add bugs/feature updates to project board
on:
  issues:
    types:
      - opened
      - labeled

jobs:
  add-issue-to-project:
    name: Add to project
    runs-on: ubuntu-latest
    steps:
      - name: Add issue
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/Smalls1652/projects/3
          github-token: ${{ secrets.PROJECTS_PAT }}
          labeled: bug, feature update
