name: Deploy HonkBot to Azure

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    tags: [ 'v*.*.*' ]
  # Push nightly builds
  schedule:
    - cron: 0 0 * * *

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3.5.3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: smallsonlinecontainerreg.azurecr.io
          username: ${{ secrets.HONKBOTAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.HONKBOTAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: smallsonlinecontainerreg.azurecr.io/honkbot:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.HONKBOTAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n honkbot-app -g honkbot-resources --server smallsonlinecontainerreg.azurecr.io --username  ${{ secrets.HONKBOTAPP_REGISTRY_USERNAME }} --password ${{ secrets.HONKBOTAPP_REGISTRY_PASSWORD }}
            az containerapp update -n honkbot-app -g honkbot-resources --image smallsonlinecontainerreg.azurecr.io/honkbot:${{ github.sha }}
